import type { Metadata } from "next";
import { Rubik, Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <header>Conteúdo</header>

        {children}

        <footer className="text-xs sm:text-lg text-center text-gray-400 py-6">
          Todos os direitos reservados aos criadores e produtores dos animes
        </footer>
      </body>
    </html>
  );
}
